version: "3.7"

services:
  postgres:
    image: postgres:15.1
    container_name: postgresql-application
    ports:
      - 5432:5432
    volumes:
      - postgres-application:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: application
      POSTGRES_PASSWORD: application

volumes:
  postgres-application: