server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: application
  devtools:
    add-properties: false
  profiles:
    default: prod
    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: application
    password: application
    url: jdbc:postgresql://localhost:5432/application?useSSL=false